### ISSUE TITLE
Why per-character boxes?

### ISSUE THREAD

**Issue by jbaiter** [Shreeshrii/tessdata4alpha#1]
According to https://github.com/tesseract-ocr/tesseract/wiki/Making-Box-Files---4.0 boxes for 4.0 only have to be per-line, not per-character. Yet, the box file in this repository contains per-character boxes. Is the wiiki page wrong or the file?

**Comment by Shreeshrii** [comment]
The box file was generated by tesseract - please see https://github.com/Shreeshrii/tessdata4alpha/blob/master/tesstrain.log

The box file has tab characters at the end of each line of text. 

I posted the files here for easy access for linking on the tesseract-ocr wiki page. Please ask tesseract related questions on tesseract forum.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-training-data by Ray
has more details
