### ISSUE TITLE
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file tessedit.cpp, line 193

### ISSUE THREAD

**Issue by dsouzaankit** [Shreeshrii/tessdata4alpha#3]
I get above error when trying to use your traineddata file in a tesseract 4.0 docker container from https://github.com/tesseract-shadow/tesseract-ocr-re.

Your traineddata file is stored in a folder named 'trained_digit' and I am running docker command as below.
docker exec -it t4re /bin/bash -c "tesseract output/Output.png stdout --tessdata-dir trained_digit -l digits"

Any ideas?

**Comment by Shreeshrii** [comment]
Are you able to use any traineddata files from tessraract-ocr/testdata_best and teesdata_fast repository.
